server:
  port: 8025

spring:
  datasource:
    username: CTV_LIBRARY
    password: 123456
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      validation-timeout: 5000
      connection-timeout: 10000
      max-lifetime: 20000
      connection-test-query: select 1 from dual
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: 'true'
    show-sql: 'true'