server:
  port: 8025

spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      validation-timeout: 5000
      connection-timeout: 10000
      max-lifetime: 1800000
      connection-test-query: select 1 from dual
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: 'true'
    show-sql: 'true'

templates:
  excel:
    folder: template/excel
    file-name:
      export-users: export_users.xlsx
      import-users: import_users.xlsx
      export-json: export_json.xlsx